### ISSUE TITLE
Javadoc's stop working

### ISSUE THREAD

**Issue by RocusHalbasch** [cnfree/Eclipse-Class-Decompiler#1]
When you have a class with no source but that has attached Javadocs, Eclipse integrates the Javadocs into the GUI in tooltips and the Javadoc view. When you use Eclipse-Class-Decompiler to decompile the class Eclipse no longer integrates the Javadocs so they can't be seen in the tooltips or Javadoc view. Instead a message stating "Note: This element has no attached source and the Javadoc could not be found in the attached Javadoc." is displayed. The Javadocs for the class will continue to be unavailable until the user closes and re-opens Eclipse. This has been a problem with other decompiler plugins I have used and is really frustrating. Ideally Javadocs would be reversed and applied to the decompiled code but if not then at least making them continue to show in tooltips would be great.

**Comment by cnfree** [comment]
Fixed it. 

Integrate the decomiler editor with java doc.

Please update the decomiler plugin to the latest version, thanks.

**Comment by RocusHalbasch** [comment]
Thanks. That was quick.

**Comment by RocusHalbasch** [comment]
Actually I just updated and the problem seems to still exist.

**Comment by cnfree** [comment]
I can't reproduce your problem with the version 2.6.0.

But I still release a new version to fix it. Please update to version 2.7.0 and try it again.

**Comment by RocusHalbasch** [comment]
Well it is working correctly now. I really like the fact that the Javadocs are visible in the tootips of the decompiled code as well. Thanks again for the quick fix.
